{% set version = "1.3.0" %}

# handle undefined PYTHON in `noarch: generic` outputs
{% if PYTHON is not defined %}{% set PYTHON = "$PYTHON" %}{% endif %}

package:
  name: sphinxcontrib-svg2pdfconverter
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/sphinxcontrib-svg2pdfconverter/sphinxcontrib_svg2pdfconverter-{{ version }}.tar.gz
  sha256: 6411a4cc2f57eed96a0d7bbfa139f68cbe7983018881e1e6d7c46053cd69911f

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - sphinx >=1.6.3

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - sphinxcontrib.cairosvgconverter
    - sphinxcontrib.inkscapeconverter
    - sphinxcontrib.rsvgconverter
  commands:
    - pip check

outputs:
  - name: sphinxcontrib-svg2pdfconverter

  - name: sphinxcontrib-svg2pdfconverter-with-cairosvg
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("sphinxcontrib-svg2pdfconverter", max_pin="x.x.x") }}
        - cairosvg >=1.0
    test:
      requires:
        - pip
      imports:
        - sphinxcontrib.cairosvgconverter
      commands:
        - pip check

  - name: sphinxcontrib-svg2pdfconverter-with-rsvg
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("sphinxcontrib-svg2pdfconverter", max_pin="x.x.x") }}
        - librsvg
    test:
      requires:
        - pip
      imports:
        - sphinxcontrib.rsvgconverter
      commands:
        - pip check

  - name: sphinxcontrib-svg2pdfconverter-with-all
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("sphinxcontrib-svg2pdfconverter-with-rsvg", max_pin="x.x.x") }}
        - {{ pin_subpackage("sphinxcontrib-svg2pdfconverter-with-cairosvg", max_pin="x.x.x") }}
    test:
      files:
        - converter_test.py
      requires:
        - coverage
        - inkscape  # [win]
        - pytest
        - pytest-console-scripts
        - tectonic
      imports:
        - sphinxcontrib
      commands:
        - python converter_test.py

about:
  home: https://github.com/missinglinkelectronics/sphinxcontrib-svg2pdfconverter
  summary: Sphinx SVG to PDF converter extension
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
