# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 1.3.0

recipe:
  name: sphinxcontrib-svg2pdfconverter
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/sphinxcontrib-svg2pdfconverter/sphinxcontrib_svg2pdfconverter_${{ version }}.tar.gz
  sha256: 6411a4cc2f57eed96a0d7bbfa139f68cbe7983018881e1e6d7c46053cd69911f

build:
  number: 0
  noarch: python

outputs:
  - package:
      name: sphinxcontrib-svg2pdfconverter
    build:
      noarch: python
      script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    requirements:
      host:
        - pip
        - python ${{ python_min }}.*
        - setuptools
      run:
        - python >=${{ python_min }}
        - sphinx >=1.6.3
    tests:
      - python:
          imports:
            - sphinxcontrib.cairosvgconverter
            - sphinxcontrib.inkscapeconverter
            - sphinxcontrib.rsvgconverter
          pip_check: true
          python_version: ${{ python_min }}.*

  - package:
      name: sphinxcontrib-svg2pdfconverter-with-cairosvg
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("sphinxcontrib-svg2pdfconverter", upper_bound="x.x.x") }}
        - cairosvg >=1.0
    tests:
      - python:
          imports: sphinxcontrib.cairosvgconverter
          pip_check: true
          python_version: ${{ python_min }}.*

  - package:
      name: sphinxcontrib-svg2pdfconverter-with-rsvg
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("sphinxcontrib-svg2pdfconverter", upper_bound="x.x.x") }}
        - librsvg
    tests:
      - python:
          imports: sphinxcontrib.rsvgconverter
          pip_check: true
          python_version: ${{ python_min }}.*

  - package:
      name: sphinxcontrib-svg2pdfconverter-with-all
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("sphinxcontrib-svg2pdfconverter-with-rsvg", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("sphinxcontrib-svg2pdfconverter-with-cairosvg", upper_bound="x.x.x") }}
    tests:
      - python:
          imports: sphinxcontrib
          pip_check: true
          python_version: ${{ python_min }}.*
      - files:
          recipe:
            - converter_test.py
        requirements:
          run:
            - coverage
            - pytest
            - pytest-console-scripts
            - tectonic
            - if: win
              then:
                - inkscape
        script:
          - python converter_test.py


about:
  summary: Sphinx SVG to PDF converter extension
  license: BSD-2-Clause
  license_file: LICENSE.txt
  homepage: https://github.com/missinglinkelectronics/sphinxcontrib-svg2pdfconverter

extra:
  recipe-maintainers:
    - bollwyvl
